name: Deploy React App to OCI

on:
  push:
    branches:
      - main

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up OCI CLI
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: "oci -v"

      - name: Configure OCI CLI
        env:
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_INSTANCE_ID: ${{ secrets.OCI_INSTANCE_ID }}
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${OCI_USER_OCID}" >> ~/.oci/config
          echo "fingerprint=${OCI_KEY_FINGERPRINT}" >> ~/.oci/config
          echo "tenancy=${OCI_TENANCY_OCID}" >> ~/.oci/config
          echo "region=${OCI_REGION}" >> ~/.oci/config
          echo "${OCI_PRIVATE_KEY}" > ~/.oci/oci_private_key.pem
          chmod 600 ~/.oci/oci_private_key.pem
          echo "key_file=~/.oci/oci_private_key.pem" >> ~/.oci/config
          chmod 600 ~/.oci/config
          echo "Config file created at ~/.oci/config"

      - name: Check if the instance is running
        run: |
            instance_state=$(oci compute instance list \
            --compartment-id $OCI_TENANCY_OCID \
            --query "data[?\"lifecycle-state\"=='RUNNING'] | sort_by(@, &\"time-created\") | [-1].\"lifecycle-state\"" \
            --output json | jq -r '.')

            while [ "$instance_state" != "RUNNING" ]; do
            sleep 10
            
            instance_state=$(oci compute instance list \
                --compartment-id $OCI_TENANCY_OCID \
                --query "data[?\"lifecycle-state\"=='RUNNING'] | sort_by(@, &\"time-created\") | [-1].\"lifecycle-state\"" \
                --output json | jq -r '.')
            done

      - name: Deploy React App to OCI
        run: |
          # Add deployment steps here
          echo "Deploying React App..."